pull_request_rules:
  - name: auto merge for the owners
    conditions:
      - "author=tianhaoz95"
    actions:
      merge:
        method: squash
  - name: auto merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
