name: PR checks

on:
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
    paths:
      - "iwfpapp/**"
      - ".github/**"
  pull_request:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
  schedule:
    - cron: 0 2 * * *

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.2'
          channel: 'stable'
      - run: cd ./iwfpapp && flutter pub get
      - run: cd ./iwfpapp && flutter analyze
      - run: cd ./iwfpapp && flutter test
